-- A CROSS JOIN clause allows you to create a Cartesian Product of rows from two or more tables. 
-- Different from other join clauses, CROSS JOIN does not have a join predicate.
-- Use this whenever you're in a "Show me all possibilities" scenario.