CREATE TABLE fruits(
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL
);

INSERT INTO fruits(name)
VALUES ('Orange');

INSERT INTO fruits
VALUES (DEFAULT, 'Apple');

SELECT * FROM fruits;

-- To get the name of a SERIAL column in a table, you use this:
-- pg_get_serial_sequence(table_name, column_name)
SELECT * FROM pg_get_serial_sequence('fruits', 'id');

-- You can pass a sequence name to the currval() to get the the recent value generated by a sequence.
-- ERROR: currval of sequence 'fruits_id_seq' is not yet defined in this session.
SELECT currval(pg_get_serial_sequence('fruits', 'id'));

-- If you want to get the value generated by the sequence when you insert a new row into the table:
INSERT INTO fruits(name)
VALUES
  ('Mango'),
  ('Banana')
RETURNING id;

/*
 * The sequence operator is not transaction safe.
 * It means that if two concurrent database connections attempt to get the next value from a sequence,
 * each client will get a different value.
 * 
 * If one client rolls back the transaction, the sequence number of that client will be unused,
 * creating a gap in the sequence. 
 * */